# -*- coding: utf-8 -*-
"""Games_Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbHlSh8NmQjsyMbCaCEhPwvsPdPHqyA3
"""

import random

def fun_game(die_sides):
  """ this is a game to roll a sued sided die 5 times"""
  die_rolls=[random.randint(1,die_sides) for die in range(5)]
  return die_rolls

def number_game():
  secret= random.randint(1,10)
  guess=int(input("Guess a number between 1 and 10:"))
  if guess==secret:
    return "you win"
  else:
    return "you lose"

fun_game(20)

number_game()